# Generated by Django 4.1.3 on 2023-01-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('van familiar', 'van familiar'), ('coche', 'coche')], max_length=50)),
                ('time', models.TimeField()),
                ('place', models.CharField(max_length=200)),
            ],
        ),
    ]
