# Generated by Django 4.1.5 on 2023-01-20 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
