# Generated by Django 4.1.5 on 2023-01-20 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_transport_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='price',
        ),
    ]
