# Generated by Django 4.1.5 on 2023-01-20 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_transport_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='time',
            field=models.FloatField(),
        ),
    ]
