# Generated by Django 4.1.5 on 2023-01-20 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_transport_options_alter_transport_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='price',
            field=models.FloatField(default=123),
            preserve_default=False,
        ),
    ]
