# Generated by Django 4.1.5 on 2023-01-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_transport_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('time', models.FloatField()),
                ('price', models.FloatField()),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
    ]
