# Generated by Django 4.1.5 on 2023-01-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_day', models.FloatField()),
                ('available', models.BooleanField(default=True)),
                ('time', models.FloatField()),
                ('space', models.FloatField()),
            ],
            options={
                'verbose_name': 'Cuarto',
                'verbose_name_plural': 'Cuartos',
            },
        ),
    ]
